# O docker-compose √© como um "Plano de Voo" autom√°tico.
# Em vez de digitar um monte de comandos, escrevemos tudo aqui.

version: '3'  # Vers√£o do manual que estamos usando.

services:
  # SERVI√áO 1: A NOSSA NAVE
  missao-web:
    build: .  # "Construa a nave usando o Dockerfile que est√° AQUI (.)"
    ports:
      # AQUI EST√Å O TRUQUE! üîå
      # "Conecte a porta 5000 do meu computador (esquerda) 
      #  na porta 5000 da nave (direita)."
      - "5000:5000"
    volumes:
       # Opcional: Para ver as mudan√ßas sem reiniciar (modo avan√ßado!)
       - .:/app
